---
proxy: ""
regions:
  syd: ap-sydney-1
  mel: ap-melbourne-1
  gru: sa-saopaulo-1
  vcp: sa-vinhedo-1
  yul: ca-montreal-1
  yyz: ca-toronto-1
  scl: sa-santiago-1
  fra: eu-frankfurt-1
  hyd: ap-hyderabad-1
  bom: ap-mumbai-1
  kix: ap-osaka-1
  nrt: ap-tokyo-1
  ams: eu-amsterdam-1
  jed: me-jeddah-1
  icn: ap-seoul-1
  yny: ap-chuncheon-1
  zrh: eu-zurich-1
  dxb: me-dubai-1
  lhr: uk-london-1
  cwl: uk-cardiff-1
  iad: us-ashburn-1
  phx: us-phoenix-1
  sjc: us-sanjose-1
